[tool.poetry]
name = "vrp"
version = "0.1.0"
description = ""
authors = ["Dmiriy Yampolkiy <yampolskiydv@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
auromat = "^1.0.8"
timezonefinder = {extras = ["numba"], version = "^4.4.1"}
utm = "^0.6.0"
geopy = "^2.0.0"
diskcache = "^5.0.3"
gmaps = "^0.9.0"
pip = "^20.2.3"
pandas = "^1.1.3"
xlrd = "^1.2.0"
geopandas = "^0.8.1"
matplotlib = "^3.3.2"
descartes = "^1.1.0"
mapclassify = "^2.3.0"
rtree = "^0.9.4"
pygeos = "^0.8"
arcgis = "^1.8.2"
herepy = "^3.0.2"
ujson = "^4.0.1"
numpy = "^1.19.2"
numba = "^0.51.2"
aiohttp = "^3.6.3"
sklearn = "^0.0"
polyline = "^1.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pytest = "^6.1.1"
pytest-pycharm = "^0.7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
